config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :answers
  get 'inertia-example', to: 'inertia_example#index'
  resources :user_prizes, only: [:index, :create]
  resources :prizes
  resources :groups
  resources :players
  resources :users, except: :show do
    patch 'update_xp', to: 'users#update_xp', on: :collection
    post 'authenticate', to: 'users#authenticate', on: :member
  end

  resources :tasks do
    post 'complete', on: :member
  end

  post 'switch_user', to: 'application#switch_user'
  resources :pokemon, except: :destroy do
    get 'new_question' => 'pokemon#new_question', on: :collection
    post 'create_round' => 'pokemon#create_round', on: :collection
    post 'submit_answer' => 'pokemon#submit_answer', on: :collection
    get 'pokedex', on: :collection
  end

  get 'store', to: 'home#store'

  resources :games do
    get 'new_pokemon_round', to: 'rounds#pokemon_new'
    get 'new_simple_math_round', to: 'rounds#simple_math_new'
    get 'new_collections_round', to: 'rounds#collections_new'
    get 'trivia', to: 'rounds#trivia'
    get 'state_selector', to: 'rounds#state_selector'
    resources :rounds, only: [] do
      get 'new_question', to: 'questions#new', on: :collection, as: 'new_question'
    end
  end

  resources :questions, except: [:create] do
    member do
      get 'edit_trivia', to: 'trivia_questions#edit', as: 'edit_trivia'
      delete 'trivia', to: 'trivia_questions#destroy'
    end
    post 'trivia_questions', to: 'trivia_questions#create', as: 'create_trivia', on: :collection
    get 'trivia', to: 'questions#trivia_questions', as: 'trivia', on: :collection
  end
  # get 'new_trivia_question', to: 'questions#new_trivia_question', as: 'new_trivia_question'
  # post

  resources :questions, only: [] do
    get 'new_simple_math', on: :collection
  end

  get 'state_selector', to: 'rounds#state_selector'

  root to: 'games#index'
  get 'landing' => 'home#landing'

  get 'sign_in' => 'users#sign_in'
  get '/auth/auth0/callback' => 'auth0#callback'
  get '/auth/failure' => 'auth0#failure'
  get '/auth/logout' => 'auth0#logout', as: 'logout'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #
end

app/models/user.rb
# frozen_string_literal: true

# user model
class User < ApplicationRecord
  has_secure_password
  validates :first_name, presence: true
  validate :birthday_is_valid_format
  validate :bank_is_not_negative
  validates :email, presence: true, if: :adult?

  def bank_is_not_negative
    errors.add(:base, 'bank cannot be negative') if bank.negative?
  end

  belongs_to :group
  has_many :tasks, foreign_key: 'assigned_user_id', dependent: :destroy
  has_many :created_tasks, class_name: 'Task', foreign_key: 'created_by_id', dependent: :destroy
  has_many :answers, dependent: :destroy
  has_many :rounds, dependent: :destroy

  enum role: { adult: 'adult', child: 'child', super: 'super' }

  def adult?
    role == 'adult' || role == 'super'
  end

  def level
    xp / 100 + 1
  end

  def level_progress
    xp % 100
  end

  def name
    [first_name, last_name].compact.join(' ')
  end

  def age
    return 'N/A' unless birthday

    today = Date.today
    age = today.year - birthday.year
    age -= 1 if today < birthday + age.years
    age
  end

  def last_group_member?
    group.users.count == 1
  end

  def icon_for_role
    adult? ? 'user' : 'child'
  end

  private

  def birthday_is_valid_format
    return unless birthday.present?

    errors.add(:birthday, 'is not a valid date') unless birthday.is_a?(Date)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new(last_name: current_user.last_name)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    @user.birthday = Date.strptime(user_params[:birthday], '%m/%d/%Y') if user_params[:birthday].present?

    if @user.update(user_params)
      redirect_to users_path, notice: 'User was successfully updated.'
    else
      render 'edit'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    @user.group_id = current_user.group_id
    @user.role = 'child'
    @user.birthday = Date.strptime(user_params[:birthday], '%m/%d/%Y') if user_params[:birthday].present?

    if @user.save
      redirect_to users_path, notice: 'User was successfully created.'
    else
      render 'new'
    end
  end

  def sign_in
    render 'sign-in'
  end

  def index
  end

  def update_xp
    bank = current_user.bank + user_params[:xp].to_i
    current_player.update(xp: current_player.xp + user_params[:xp].to_i, bank:)
    current_player.update!(xp: current_player.xp + user_params[:xp].to_i)
    render json: { xp: current_player.xp, level: current_player.level, level_progress: current_player.level_progress }, status: :ok
  end

  def destroy
    @user = User.find(params[:id])
    if @user.last_group_member?
      redirect_to users_path, notice: 'User is the last member of a group and cannot be deleted.'
      return
    end
    @user.destroy

    redirect_to users_path, notice: 'User was successfully deleted.'
  end

  def authenticate
    @user = User.find_by(id: params[:id])
    return render json: { success: true }, status: :ok if @user.password_digest.blank?

    if @user&.authenticate(params[:password])
      session[:user_id] = @user.id
      render json: { success: true }, status: :ok
    else
      render json: { success: false, errors: 'Incorrect password' }, status: :unauthorized
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :password, :password_confirmation, :birthday, :xp)
  end
end

app/views/users/_form.html.erb
<div x-data="userForm">
  <%= form_with model: @user, html: { style: 'width: fit-content', id: 'user-form' } do |f| %>
    <div class="md:flex items-center mt-6">
      <div class="md:w-64">
        <label class="text-sm leading-none text-gray-800" id="firstName">First name</label>
        <%= f.text_field :first_name, class: "w-full p-3 mt-3 bg-gray-100 border rounded border-gray-200 focus:outline-none focus:border-gray-600 text-sm font-medium leading-none text-gray-800", ariaLabelledby: "firstName", placeholder: "John", tabIndex: 0 %>
      </div>
      <div class="md:w-64 md:ml-12 md:mt-0 mt-4">
        <label class="text-sm leading-none text-gray-800" id="lastName">Last name</label>
        <%= f.text_field :last_name, class: "w-full p-3 mt-3 bg-gray-100 border rounded border-gray-200 focus:outline-none focus:border-gray-600 text-sm font-medium leading-none text-gray-800", ariaLabelledby: "lastName", placeholder: "Doe", tabIndex: 1 %>
      </div>
    </div>

    <div class="md:flex items-center justify-between mt-6">

      <div class="md:w-64 md:mt-0 mt-4">
        <label class="text-sm leading-none text-gray-800" id="email">Email</label>
        <%= f.email_field :email, class: "w-full p-3 mt-3 bg-gray-100 border rounded border-gray-200 focus:outline-none focus:border-gray-600 text-sm font-medium leading-none text-gray-800", ariaLabelledby: "email", placeholder: "john@example.com", tabIndex: 4 %>
      </div>

      <div class="md:w-64">
        <label class="text-sm leading-none text-gray-800" id="birthday">Birthday</label>

        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
        <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>

        <div
          x-data="{
        value: [Date.now()],
        init() {
            let picker = flatpickr(this.$refs.picker, {
                allowInput: true,
                dateFormat: 'm/d/Y',
                defaultDate: this.value,
                onChange: (date, dateString) => {
                    this.value = dateString.split(' to ')
                }
            })
            this.$watch('value', () => picker.setDate(this.value))
        },
        }"
          class="max-w-sm w-full"
        >
          <%= f.date_field :birthday, 'x-ref': 'picker', class: "w-full p-3 mt-3 bg-gray-100 border rounded border-gray-200 focus:outline-none focus:border-gray-600 text-sm font-medium leading-none text-gray-800", ariaLabelledby: "birthday", placeholder: "08/18/2018", tabIndex: 2 %>

        </div>
      </div>
    </div>

    <div class="md:flex items-center mt-6">
      <div class="md:w-64">
        <label class="text-sm leading-none text-gray-800" id="firstName">Password</label>
        <%= f.password_field :password, class: "w-full p-3 mt-3 bg-gray-100 border rounded border-gray-200 focus:outline-none focus:border-gray-600 text-sm font-medium leading-none text-gray-800", ariaLabelledby: "firstName", placeholder: "Enter password", tabIndex: 2 %>
      </div>
      <div class="md:w-64 md:ml-12 md:mt-0 mt-4">
        <label class="text-sm leading-none text-gray-800" id="lastName">Password Confirmation</label>
        <%= f.password_field :password_confirmation, class: "w-full p-3 mt-3 bg-gray-100 border rounded border-gray-200 focus:outline-none focus:border-gray-600 text-sm font-medium leading-none text-gray-800", ariaLabelledby: "lastName", placeholder: "Enter password", tabIndex: 3 %>
      </div>
    </div>

    <div class="md:flex items-center mt-6">
      <div class="md:w-64">
        <label class="text-sm leading-none text-gray-800" id="role">Role</label>
        <%= f.select :role, User.roles.keys.map{|role| [role.capitalize, role]}, { include_blank: 'Select Role' }, class: "w-full p-3 mt-3 bg-gray-100 border rounded border-gray-200 focus:outline-none focus:border-gray-600 text-sm font-medium leading-none text-gray-800", ariaLabelledby: "role", tabIndex: 5 %>
      </div>
    </div>

    <% if @user&.errors&.any? %>
      <div id="error_explanation">

        <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li class="text-red-800 font-light mt-4"><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="my-6 flex items-center justify-between">
      <button class="btn primary">
        <%= @user.new_record? ? 'Add User' : 'Save' %>
      </button>
      <div class="flex items-center justify-between gap-3">
        <% if @user.persisted? %>
          <button @click.prevent.stop="deleteUser" class="btn danger">
            Delete User
          </button>
        <% end %>
        <button class="btn secondary">
          <%= link_to 'Cancel', users_path %>
        </button>
      </div>
    </div>
  <% end %>
</div>

<script type="text/javascript" charset="utf-8">
    const form = document.getElementById('user-form')
    document.addEventListener('alpine:init', () => {
        Alpine.data('userForm', () => ({
            deleteUser(e) {
                e.preventDefault()
                if (confirm('Are you sure you want to delete this user?')) {
                    form.querySelector('[name="_method"]').value = 'delete'
                    form.submit()
                }

            }
        }))
    })
</script>

app/views/users/edit.html.erb
<div class="lg:ml-24 mt-10">
  <h1 class="text-2xl font-bold tracking-wide">Edit User</h1>
  <%= render partial: 'form', user: @user %>
</div>

app/views/users/index.html.erb
<!-- page heading -->

<div class="bg-white px-5 sm:px-10">
  <div class="py-6 container mx-auto flex flex-col md:flex-row items-start md:items-center justify-between">
    <div>
      <p class="flex items-center text-yellow-400 text-xs">
        <span>Home</span>
        <span class="mx-2">&gt;</span>
        <span>Students</span>
      </p>
      <h4 class="text-2xl font-bold leading-tight text-gray-800">
        Students
      </h4>
    </div>
    <div class="mt-6 md:mt-0">
      <%= link_to new_user_path, class: 'btn secondary flex items-center gap-3' do  %>
        <box-icon type='solid' name='user-plus'></box-icon>
        <span>Add A Student</span>
      <% end %>
    </div>
  </div>
</div>

<!-- cards -->
<div class="container w-11/12 mx-auto grid sm:grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-3 my-12 gap-8">
  <% @players.each do |player| %>

    <div class="bg-white shadow-md flex flex-col items-center p-8 rounded">
      <div class="h-24 w-24 p-2 bg-gray-100 rounded-full mb-1">
        <img src="https://tuk-cdn.s3.amazonaws.com/assets/templates/Education-Portal/ep_17.png" alt="" class="h-full w-full object-cover overflow-hidden rounded-full"/>
      </div>
      <p class="mb-1 text-gray-800 text-base font-normal">
        <%= player.name %>
      </p>
      <!--            <p class="mb-6 text-gray-600 text-xs">B.A. Business Administration</p>-->
      <div class="flex w-full justify-between mb-8">
        <div class="flex flex-col items-center w-4/12">
          <p class="text-gray-600 text-2xl"><%= player.age %></p>
          <p class="text-gray-800 text-sm">Age</p>
        </div>

        <div class="flex flex-col items-center w-4/12 border-r border-l border-gray-200">
          <p class="text-gray-600 text-2xl"><%= player.level %></p>
          <p class="text-gray-800 text-sm">LEVEL</p>
        </div>
        <div class="flex flex-col items-center w-4/12">
          <p class="text-gray-600 text-2xl"><%= player.level_progress %></p>
          <p class="text-gray-800 text-sm">XP</p>
        </div>
      </div>
      <% can_edit = current_user.id == player.id || current_user.adult? %>
      <div class="flex items-center justify-between mb-8 gap-3">
        <div class="<%= 'opacity-0 pointer-events-none' unless can_edit %>">
          <%= link_to 'Edit Profile', edit_user_path(player.id), class: 'btn info' %>
        </div>
        <%= link_to 'Purchase History', user_prizes_path(user_id: player.id), class: 'btn primary' %>
      </div>
    </div>
  <% end %>
</div>
<script>
    // Avatar Dropdown
    function dropdownHandler(element) {
        let single = element.getElementsByTagName("ul")[0];
        single.classList.toggle("hidden");
    }

    //Hamburger and mobile menu
    function MenuHandler(el, val) {
        let MainList = el.parentElement.parentElement.getElementsByTagName(
            "ul"
        )[0];
        let closeIcon = el.parentElement.parentElement.getElementsByClassName(
            "close-m-menu"
        )[0];
        let showIcon = el.parentElement.parentElement.getElementsByClassName(
            "show-m-menu"
        )[0];
        if (val) {
            MainList.classList.remove("hidden");
            el.classList.add("hidden");
            closeIcon.classList.remove("hidden");
        } else {
            showIcon.classList.remove("hidden");
            MainList.classList.add("hidden");
            el.classList.add("hidden");
        }
    }
</script>
</body>

</html>

app/views/users/new.html.erb
<div class="lg:ml-24 mt-10">
  <h1 class="text-2xl font-bold tracking-wide">Add A New User</h1>
  <%= render partial: 'form' %>
</div>